all: exercicio1 exercicio2 exercicio3 exercicio4 exercicio5 exercicio6

exercicio1: exercicio1.pas
	fpc exercicio1.pas
exercicio2: exercicio2.pas
	fpc exercicio2.pas
exercicio3: exercicio3.pas
	fpc exercicio3.pas
exercicio4: exercicio4.pas
	fpc exercicio4.pas
exercicio5: exercicio5.pas
	fpc exercicio5.pas
exercicio6: exercicio6.pas
	fpc exercicio6.pas

clean:
	rm *.o *~ exercicio[1-6]
