all: ponteiro1 ponteiro2 ponteiro3

ponteiro1: ponteiro1.pas
	fpc ponteiro1.pas
ponteiro2: ponteiro2.pas
	fpc ponteiro2.pas
ponteiro3: ponteiro3.pas
	fpc ponteiro3.pas
clean:
	rm *.o *~ ponteiro[1-6]
