"if has("vms")
"    set nobackup      " do not keep a backup file, use versions instead
"else
"    set backup        " keep a backup file
"endif
"
"set directory=~/.backup-vim
"set backupdir=~/.backup-vim
"
"
""color evening
"set encoding=utf8
"set paste
"set expandtab
"set textwidth=0
"set tabstop=4
"set softtabstop=4
"set shiftwidth=4
"set autoindent
"set backspace=indent,eol,start
"set incsearch
""set ignorecase
"set ruler
"set wildmenu
"set commentstring=\ #\ %s
"set foldlevel=0
"set clipboard+=unnamed
"syntax on
"
"""""""""""""'
"
"set nocompatible
"set showmatch
"set showmode
"set ts=4
"set sw=4
"set smartindent
"set number
"autocmd FileType python runtime! autoload/pythoncomplete.vim

filetype plugin on
"filetype indent on


"imap <c-space> <c-x><c-o>
":set backspace=2

"if has("autocmd")
"   au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
"               \| exe "normal g'\"" | endif
"endif

" Mappings
"nmap <C-N> :noh <CR>

"highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%81v.\+/

let g:pydiction_location = '/home/liquuid/.vim/after/ftplugin/pydiction/complete-dict'

