all: ponteiro1 ponteiro2

ponteiro: ponteiro1.pas
	fpc ponteiro1.pas
ponteiro: ponteiro2.pas
	fpc ponteiro2.pas
#exercicio3: exercicio3.pas
#	fpc exercicio3.pas
#exercicio4: exercicio4.pas
#	fpc exercicio4.pas
#exercicio5: exercicio5.pas
#	fpc exercicio5.pas
#exercicio6: exercicio6.pas
#	fpc exercicio6.pas

clean:
	rm *.o *~ ponteiro[1-6]
